# docker-compose example

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    volumes: 
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      # shared certs volume
      - ./certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"

  certimate:
    image: registry.cn-shanghai.aliyuncs.com/maxwen/certimate-docker:latest
    container_name: certimate
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro  # connect to host docker daemon
      - ./volumes/certimate:/app/pb_data
      # shared certs volume
      - ./certs:/etc/certs
    ports:
      - 8090:8090
